### ISSUE TITLE
csconv function in poolR

### ISSUE THREAD

**Issue by jazberna1** [ozancinar/poolr#3]
Hello Wolfgang,

I have some legacy code that uses a csconv function that is combined with fisher() to get the pvalues correlation.

I don't get to see that function anymore. I was wondering whether it has been deprecated and/or substituted by another one.

Many thanks for your help
Jorge

**Comment by ozancinar** [comment]
Hello Jorge,

I just got another mail from someone else on this issue. I don't know if
he/she is your colleague (sorry I can't give the name in case I am making a
wrong assumption). If so, I wrote a more detailed answer to that person it
might be helpful to you as well. If not, please contact me and I'll try to
answer this issue in more details.

But, in short, we have removed the csconv() functionality from the
poolr package last year. I checked our commits, and we specifically removed
it on September 13, 2019. I guess it should be possible for you to clone an
older version of the repo using the SHA code of the previous commits.
Maybe, this could help you if you need to use csconv() specifically.
However, please try this at your own risk, because I am not sure what
syntax changes have been made in the package since then. So, the most
recent help files/documents may not be helpful when you use an older
version. You can contact me on this, I'll do my best to help you if you
have problems with the old syntax.

Best,
ozan




Jorge Zamora <notifications@github.com>, 1 Haz 2020 Pzt, 12:00 tarihinde
şunu yazdı:

**Comment by jazberna1** [comment]
Hi Ozan,

Yes, we work both together so I got your answer to her.

Thanks so much!
Jorge

**Comment by wviechtb** [comment]
Just as a follow-up: We will probably add functionality along the lines of `csconv()` back in the future, but this will require extensive testing.

**Comment by jazberna1** [comment]
Hello,

We have some legacy code that uses a version of the csconv function that takes one parameter only (p). I was wondering if you could please point me to the relevant commit so I could have that code back (at my own risk).

Thanks
Jorge

**Comment by ozancinar** [comment]
Hello Jorge,

First, thanks for using our package.

We added the csconv() function on July 5, 2019. Here's the link to this
commit:
https://github.com/ozancinar/poolr/commit/8095cac2e07ae551ddfdc8278669aac3e1eddbf0

The last commit we made before removing the csconv functionality was
submitted on September 11, 2019 that can be found here:
https://github.com/ozancinar/poolr/commit/8e68074c11fd22b6581da98e849f67bfea393fa9

We did not make changes in the csconv() function in between these two
commits. So, I think you can use any of them, although the more recent
commit may be more appropriate as it has more updates in other functions.
Also, note that the name of the package was poolR on July 5 and it had been
changed to poolr before the commit on September 11, just to avoid conflicts
in your R environment.

And, just for clarification, the csconv() function always had two
arguments. The first argument is p that you mentioned. The other argument
is target which was used to set the target distribution that you want to
use for combining p-values. The target argument can be set by the function
itself when you use the csconv() function in a base function (i.e.,
fisher(), bonferroni(), etc.), so you can use the csconv() function by
specifying only the p argument in such a case (which is I think what you
asked). If you will be using the csconv() function by itself, you will also
need the specify the target argument. Please see the help page with ?csconv
after loading the commit you prefer to use.

Please contact me if you need further assistance.

Best,
ozan


Jorge Zamora <notifications@github.com>, 31 Tem 2020 Cum, 07:57 tarihinde
şunu yazdı:

**Comment by jazberna1** [comment]
Hi,

Thanks a lot, that was clarifying.
I am closing this one.

Regards
Jorge
